{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-binding-controller-config
  namespace: {{ .Values.controller.namespace }}
  labels:
    {{- include "fleet-bindings.labels" . | nindent 4 }}
data:
  cluster-selector.json: |
    {{- .Values.controller.clusterSelector | toPrettyJson | nindent 4 }}
{{- end }}
