apiVersion: v2
name: fleet-bindings
description: >-
  Installs the fleet binding controller, which reconciles vCP ArgoCDApplication
  bindings from Cluster metadata and automatically classified tenant clusters.
type: application
version: 0.6.0
appVersion: "0.6.0"
keywords:
  - vcluster-platform
  - argocd
  - fleet-management
sources:
  - https://github.com/loft-demos/vcluster-fleet-gitops/tree/main/bindings
  - https://github.com/loft-demos/vcluster-fleet-gitops/tree/main/controllers/fleet-binding-controller
